apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
      - name: finance
        image: financeacr123.azurecr.io/finance-app:v1
        ports:
        - containerPort: 5000