name: CI-CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name financeacr123

    - name: Build Docker Image
      run: docker build -t financeacr123.azurecr.io/finance-app:latest .

    - name: Push Docker Image
      run: docker push financeacr123.azurecr.io/finance-app:latest

    - name: Set AKS Context
      run: az aks get-credentials --resource-group finance-rg --name finance-aks --overwrite-existing

    - name: Deploy to AKS
      run: kubectl rollout restart deployment finance-app
